### PR TITLE
Simple `outputDevices` value comparison

### PR DESCRIPTION
**Pull request by sebbo2002**

### CODE REVIEW

**Comment by maxileith** [comment]
Sorry to bother you again, I haven´t look at it close enough ...

This does not really compare it correct, see screenshot. I would just leave the check out or do it with a true deepEqual. I think a solution that solves only half of the problem is worse then leaving it out ...


image

A deepEqual might truely be overkill, so I think the best option now is to revert this PR and leave everything like before.

Sorry about beeing so picky ^^

**Comment by maxileith** [comment]
Please forget the last comment :)

**Comment by maxileith** [comment]
I need one more sec to evaluate this ... please do not revert yet

**Comment by sebbo2002** [comment]
@maxileith Ou. I forgot to add `.identifier`. Sure, you can't sort objects, but you can sort the array by their identifier. Thanks for "beeing so picky", I really appreciate it.

**Pull request merged**
